### ISSUE TITLE
collect throws an error in a hub without any model output files

### ISSUE THREAD

**Issue by elray1** [Infectious-Disease-Modeling-Hubs/hubData#4]
If I run the following in a hub that contains no model output files:

```r
library(hubUtils)
library(dplyr)

model_outputs <- hubUtils::connect_hub(hub_path = ".") %>%
  dplyr::collect()
```

I get this error:

```
Error in `UseMethod()`:
! no applicable method for 'collect' applied to an object of class "c('hub_connection', 'list')"
Backtrace:
 1. hubUtils::connect_hub(hub_path = ".") %>% dplyr::collect()
 2. dplyr::collect(.)
```

**Comment by annakrystalli** [comment]
Thanks for the report @elray1 ! This is a result of a conscious prior decision to not error when connecting to an empty hub.  Using `connect_hub` on an empty hub still loads config metadata but the subclass is an empty list instead of an arrow dataset. Hence `dplyr::collect` doesn't have a method for it and fails.

This would likely be difficult to fix from within `connect_hub()` but it made me think of a somewhat related discussion @nickreich had raised a while ago (transferred to an issue in this repo: #13 ) in which the ability to run `as_model_out_tbl()` on the results of `collect` by default was proposed through a `collect_hub()` function. Such a function would be an ideal place to handle the empty hub exception too.

Note that one thing we could also do is rather than have a different function (`collect_hub()`) we could have a `collect()` S3 method of our own that is dispatched on `hub-connection` class objects.

**Comment by elray1** [comment]
I like the dea of our own `collect` method
